package com.winston.mapper;

import com.winston.entity.Excel;
import com.winston.entity.ExcelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExcelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    long countByExample(ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int deleteByExample(ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int insert(Excel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int insertSelective(Excel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    List<Excel> selectByExample(ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    Excel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Excel record, @Param("example") ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Excel record, @Param("example") ExcelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Excel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table excel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Excel record);
}