package com.winston.mapper;

import com.winston.entity.Leader;
import com.winston.entity.LeaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    long countByExample(LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int deleteByExample(LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int insert(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int insertSelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    List<Leader> selectByExample(LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    Leader selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Leader record, @Param("example") LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Leader record, @Param("example") LeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Leader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Leader record);
}