package com.winston.mapper;

import com.winston.entity.MeetingLeader;
import com.winston.entity.MeetingLeaderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeetingLeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_leader
     *
     * @mbg.generated
     */
    long countByExample(MeetingLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_leader
     *
     * @mbg.generated
     */
    int deleteByExample(MeetingLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_leader
     *
     * @mbg.generated
     */
    int insert(MeetingLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_leader
     *
     * @mbg.generated
     */
    int insertSelective(MeetingLeader record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_leader
     *
     * @mbg.generated
     */
    List<MeetingLeader> selectByExample(MeetingLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_leader
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MeetingLeader record, @Param("example") MeetingLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_leader
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MeetingLeader record, @Param("example") MeetingLeaderExample example);
}