package com.winston.mapper;

import com.winston.entity.Meetingroom;
import com.winston.entity.MeetingroomExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MeetingroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    long countByExample(MeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int deleteByExample(MeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int insert(Meetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int insertSelective(Meetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    List<Meetingroom> selectByExample(MeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    Meetingroom selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Meetingroom record, @Param("example") MeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Meetingroom record, @Param("example") MeetingroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Meetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Meetingroom record);
}