package com.winston.entity;

import java.io.Serializable;

public class Meetingroom implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.num
     *
     * @mbg.generated
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.row
     *
     * @mbg.generated
     */
    private Integer row;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meetingroom.col
     *
     * @mbg.generated
     */
    private Integer col;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meetingroom
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.id
     *
     * @return the value of meetingroom.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.id
     *
     * @param id the value for meetingroom.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.name
     *
     * @return the value of meetingroom.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.name
     *
     * @param name the value for meetingroom.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.type
     *
     * @return the value of meetingroom.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.type
     *
     * @param type the value for meetingroom.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.num
     *
     * @return the value of meetingroom.num
     *
     * @mbg.generated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.num
     *
     * @param num the value for meetingroom.num
     *
     * @mbg.generated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.row
     *
     * @return the value of meetingroom.row
     *
     * @mbg.generated
     */
    public Integer getRow() {
        return row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.row
     *
     * @param row the value for meetingroom.row
     *
     * @mbg.generated
     */
    public void setRow(Integer row) {
        this.row = row;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meetingroom.col
     *
     * @return the value of meetingroom.col
     *
     * @mbg.generated
     */
    public Integer getCol() {
        return col;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meetingroom.col
     *
     * @param col the value for meetingroom.col
     *
     * @mbg.generated
     */
    public void setCol(Integer col) {
        this.col = col;
    }
}